# Generated by Django 4.1.7 on 2023-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.CharField(default='index', max_length=100, verbose_name='index_field'),
            preserve_default=False,
        ),
    ]
